---
# tasks file for optional-features

- name: 'Include optional features'
  ansible.builtin.include_tasks: optional_features.yml
  loop: '{{ optional_features | dict2items }}'
  loop_control:
    loop_var: optional_feature
  tags:
    - configuration
