---
# tasks file for optional-features

- name: 'Windows : {{ optional_feature.key }} {{ optional_feature.value }}'
  ansible.windows.win_dsc:
    resource_name: WindowsOptionalFeature
    Name: '{{ optional_feature.key }}'
    Ensure: "{{ 'Enable' if optional_feature.value else 'Disable' }}"
