---
# tasks file for directories

- name: 'Include directories'
  ansible.builtin.include_tasks: directories.yml
  loop: '{{ directories }}'
  loop_control:
    loop_var: directory
  tags:
    - configuration
