---
# tasks file for directories

- name: 'Create directory {{ directory.main }}\{{ subdirectories }}'
  ansible.windows.win_file:
    path: '{{ directory.main }}\\{{ subdirectories }}'
    state: directory
  tags:
    - configuration
