---
# tasks file for scheduled_tasks

- name: 'Include scheduled tasks'
  ansible.builtin.include_tasks: 'scheduled_task.yml'
  loop: '{{ scheduled_tasks }}'
  loop_control:
    loop_var: scheduled_task
  tags:
    - configuration
