---
# tasks file for kdcloud.win_disk

- name: 'Retrieve disk information'
  community.windows.win_disk_facts:

- name: 'Include disk'
  ansible.builtin.include_tasks: disks.yml
  loop: '{{ disks }}'
  loop_control:
    loop_var: disk
