---
# tasks file for files

- name: "Create {{ file.path }}\\{{ file.name }}.{{ file.extension }}"
  ansible.windows.win_copy:
    dest: "{{ file.path }}\\{{ file.name }}.{{ file.extension }}"
    content: '{{ file.content | to_nice_json }}'
    state: "{{ file.state | default('present') }}"
