---
# tasks file for files

- name: 'Include directories role'
  ansible.builtin.include_role:
    name: directories
  vars:
    directories:
      - main: '{{ file.path }}'
  loop: '{{ files }}'
  loop_control:
    loop_var: file
  tags:
    - configuration

- name: 'Include file type'
  ansible.builtin.include_tasks: '{{ file.type }}.yml'
  loop: '{{ files }}'
  loop_control:
    loop_var: file
  tags:
    - configuration
